coverage:
  status:
    project:
      default:
        informational: false
        threshold: 0%
    patch:
      default:
        informational: false
        threshold: 0%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
