//! Detection for `CREATE TABLE` with SERIAL pseudo-types.
//!
//! `SERIAL` / `BIGSERIAL` / `SMALLSERIAL` are PostgreSQL pseudo-types (not
//! standard SQL). PostgreSQL 10+ provides SQL-standard identity columns
//! (`GENERATED ... AS IDENTITY`) as the preferred replacement.

use crate::checks::pg_helpers::{NodeEnum, column_type_name, is_serial_pattern, range_var_name};
use crate::checks::{Check, Config};
use crate::violation::Violation;

pub struct CreateTableSerialCheck;

impl Check for CreateTableSerialCheck {
    fn check(&self, node: &NodeEnum, _config: &Config) -> Vec<Violation> {
        let NodeEnum::CreateStmt(create_stmt) = node else {
            return vec![];
        };

        let table_name = create_stmt
            .relation
            .as_ref()
            .map(range_var_name)
            .unwrap_or_default();

        create_stmt
            .table_elts
            .iter()
            .filter_map(|elt| match &elt.node {
                Some(NodeEnum::ColumnDef(col)) if is_serial_pattern(col) => {
                    let column_name = &col.colname;
                    let serial_type = column_type_name(col);
                    let identity_type = identity_sql_type(&serial_type);
                    let operation: String = "CREATE TABLE with SERIAL".into();

                    Some(Violation::new(
                        operation,
                        format!(
                            "Column '{column}' in CREATE TABLE '{table}' uses {serial_type} which is a PostgreSQL pseudo-type (non-standard SQL). \
                            SERIAL also creates a separately-owned sequence object, which can complicate permissions, dump/restore, and replication workflows.",
                            column = column_name, table = table_name
                        ),
                        format!(
                            "Use SQL-standard identity columns instead:\n   CREATE TABLE {table} ({column} {identity_type} GENERATED BY DEFAULT AS IDENTITY);",
                            table = table_name,
                            column = column_name,
                            identity_type = identity_type
                        ),
                    ))
                }
                _ => None,
            })
            .collect()
    }
}

fn identity_sql_type(serial_type: &str) -> &'static str {
    match serial_type {
        "smallserial" => "SMALLINT",
        "bigserial" => "BIGINT",
        _ => "INTEGER",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checks::test_utils::parse_sql;
    use crate::{assert_allows, assert_detects_violation};

    #[test]
    fn test_detects_create_table_with_serial() {
        assert_detects_violation!(
            CreateTableSerialCheck,
            "CREATE TABLE users (id SERIAL PRIMARY KEY);",
            "CREATE TABLE with SERIAL"
        );
    }

    #[test]
    fn test_detects_create_table_with_bigserial() {
        assert_detects_violation!(
            CreateTableSerialCheck,
            "CREATE TABLE events (id BIGSERIAL PRIMARY KEY);",
            "CREATE TABLE with SERIAL"
        );
    }

    #[test]
    fn test_detects_create_table_with_smallserial() {
        assert_detects_violation!(
            CreateTableSerialCheck,
            "CREATE TABLE users (id SMALLSERIAL PRIMARY KEY);",
            "CREATE TABLE with SERIAL"
        );
    }

    #[test]
    fn test_allows_create_table_with_identity() {
        assert_allows!(
            CreateTableSerialCheck,
            "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);"
        );
    }

    #[test]
    fn test_allows_alter_table_add_serial() {
        assert_allows!(
            CreateTableSerialCheck,
            "ALTER TABLE users ADD COLUMN id SERIAL;"
        );
    }

    #[test]
    fn test_ignores_other_statements() {
        assert_allows!(
            CreateTableSerialCheck,
            "CREATE INDEX idx_users_email ON users(email);"
        );
    }

    #[test]
    fn test_detects_safe_alternative_without_forced_primary_key_for_non_pk_column() {
        let stmt = parse_sql("CREATE TABLE users (event_no SERIAL, name TEXT);");
        let violations = CreateTableSerialCheck.check(&stmt, &Config::default());

        assert_eq!(violations.len(), 1, "Expected exactly 1 violation");
        assert_eq!(violations[0].operation, "CREATE TABLE with SERIAL");
        assert!(
            violations[0]
                .safe_alternative
                .contains("GENERATED BY DEFAULT AS IDENTITY")
        );
        assert!(!violations[0].safe_alternative.contains("PRIMARY KEY"));
    }
}
