-- Safe: BIGINT and identity-backed BIGINT primary keys
-- These avoid ID exhaustion

-- BIGINT primary key
CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    name TEXT
);

-- Identity-backed BIGINT primary key (auto-incrementing BIGINT)
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT
);

-- Composite PK with all BIGINT columns
CREATE TABLE events (
    tenant_id BIGINT,
    event_id BIGINT,
    PRIMARY KEY (tenant_id, event_id)
);

-- INT is safe for non-PK columns
CREATE TABLE lookups (
    id BIGINT PRIMARY KEY,
    code INT UNIQUE,
    name TEXT
);
